export enum CreepTask {
    Base = 'base',
    Harvest = 'harvest',
    Transfer = 'transfer',
    Withdraw = 'withdraw',
    Build = 'build',
    Repair = 'repair',
    Idle = 'Idle',
    Move = 'move',
    Sleep = 'sleep',
    AttackMelee = 'attackMelee',
    AttackRanged = 'attackRanged',
    Pickup = 'pickup',
    Regen = 'regen',
}
